#!/usr/bin/env python3
"""Generate the headless overlay for a dsh agent preset from the single workflow source.

Single source of truth = <repo>/packages/preset/agent-presets/presets/<preset>/workflow.md

The overlay is a GENERATED ARTIFACT: it inlines a verbatim copy of the workflow text.
=> It MUST be regenerated after EVERY workflow.md change, otherwise headless sessions run
   stale instructions while the Web preset reads the live file. (2026-09-03 lesson: the
   equity-research overlay did not exist at all, so headless had no Route S instructions.)

Usage:
    python gen_headless_overlay.py                      # macro-analysis (default)
    python gen_headless_overlay.py --preset equity-research
"""
from __future__ import annotations

import argparse
from pathlib import Path

# preset root moved (v0.1.2-alpha.3) from apps/cli/config/agent-presets to
# packages/preset/agent-presets/presets; ~/.dsh keeps a deployment copy as fallback.
# Candidate order mirrors the persona lookup in presets/*/agent.cordis.yml.
REPO_ROOT = Path(__file__).resolve().parents[2]
PRESETS_ROOT = REPO_ROOT / "packages" / "preset" / "agent-presets" / "presets"

IDENTITY = {
    "macro-analysis": """You are the macro-analysis Agent, a macroeconomic data collection and cleaning specialist.
Working directory: {{cwd}}. Your mission is to collect fixed China/US macro indicators on a release-calendar
and daily-vintage basis, preserve revision history, and build a cleaned macro-analysis database exposed
read-only through a local MCP server. The four phases are Collect -> Verify -> Store -> Clean. Never fabricate
data; make no predictions and no forecasts.""",
    "equity-research": """You are the equity-research Agent (投研助理), an A-share risk-screening and
investment-research assistant.
Working directory: {{cwd}}. Your mission is to answer "what is this stock's verified risk status" using three
real-data layers: (1) verified risk labels - margin crowding and agriculture earnings neglists;
(2) descriptive diagnostics (Route S): coverage gate -> data-quality verdict -> price/volume profile ->
benchmark comparison (Newey-West t) -> fundamental time series; (3) real-world evidence - news, exchange
announcements and sell-side research pulled from LIVE APIs (ashare_evidence.py), never invented.
A-share alpha research is CLOSED and must not be reopened - you do NOT pick stocks and do NOT produce
buy/sell signals.
HARD RULES: every textual claim (news / announcement / research) must come from a real API call and must be
cited with source + URL + timestamp; the LLM must never invent, paraphrase-from-memory or guess text.
Never fabricate data or engine output. Never emit buy/sell advice, price targets, position sizing or timing
signals. Every conclusion requires a human gate.""",
}


def indent(text: str, n: int = 6) -> str:
    pad = " " * n
    return "\n".join((pad + line if line.strip() else "") for line in text.splitlines())


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--preset", default="macro-analysis", choices=sorted(IDENTITY))
    preset = ap.parse_args().preset

    workflow_md = PRESETS_ROOT / preset / "workflow.md"
    if not workflow_md.is_file():
        workflow_md = Path.home() / ".dsh" / ".agent-presets" / preset / "workflow.md"
    if not workflow_md.is_file():
        raise SystemExit(f"workflow source not found for preset '{preset}'")

    header = (
        f"# Generated by scripts/macro-analysis/gen_headless_overlay.py --preset {preset}; "
        "do not hand-edit workflow text.\n"
        f"# Single source: packages/preset/agent-presets/presets/{preset}/workflow.md\n"
        "# (v0.1.2-alpha.3 moved presets out of apps/cli/config/agent-presets)\n"
        "# GENERATED: regenerate after every workflow.md change (the overlay inlines a copy).\n"
        "- id: system-prompt\n"
        "  config:\n"
        "    persona: |\n"
    )

    out_yml = Path(__file__).with_name(f"{preset}-headless.yml")
    workflow = workflow_md.read_text(encoding="utf-8").rstrip()
    out_yml.write_text(header + indent(IDENTITY[preset]) + "\n\n" + indent(workflow) + "\n", encoding="utf-8")
    print(f"generated {out_yml} from {workflow_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
