#!/usr/bin/env python3
"""Generate the headless macro-analysis overlay from the single workflow source."""
from __future__ import annotations

from pathlib import Path

# 单一事实源 = 仓库内的 preset workflow.md（git 跟踪）。
# 之前读 ~/.dsh/.agent-presets/macro-analysis/workflow.md 会导致 home 部署副本与仓库副本漂移
# （home 副本仍用旧 `scripts/` 路径、且缺 NBS 官方一手源描述）。
#
# preset root 自 v0.1.2-alpha.3 起由 apps/cli/config/agent-presets 迁至
# packages/preset/agent-presets/presets（旧目录已删除）。保留 ~/.dsh 部署副本兜底，
# 候选顺序与 presets/*/agent.cordis.yml 的 persona 读取顺序一致。
REPO_ROOT = Path(__file__).resolve().parents[2]
PRESET_DIR = REPO_ROOT / "packages" / "preset" / "agent-presets" / "presets" / "macro-analysis"
HOME_PRESET_DIR = Path.home() / ".dsh" / ".agent-presets" / "macro-analysis"
WORKFLOW_MD = PRESET_DIR / "workflow.md"
if not WORKFLOW_MD.is_file():
    WORKFLOW_MD = HOME_PRESET_DIR / "workflow.md"
OUT_YML = Path(__file__).with_name("macro-analysis-headless.yml")

IDENTITY = """You are the macro-analysis Agent, a macroeconomic data collection and cleaning specialist.
Working directory: {{cwd}}. Your mission is to collect fixed China/US macro indicators on a release-calendar
and daily-vintage basis, preserve revision history, and build a cleaned macro-analysis database exposed
read-only through a local MCP server. The four phases are Collect -> Verify -> Store -> Clean. Never fabricate
data; make no predictions and no forecasts."""

HEADER = """# Generated by scripts/macro-analysis/gen_headless_overlay.py; do not hand-edit workflow text.
# Single source: packages/preset/agent-presets/presets/macro-analysis/workflow.md
# (v0.1.2-alpha.3 moved presets out of apps/cli/config/agent-presets)
- id: system-prompt
  config:
    persona: |
"""


def indent(text: str, n: int = 6) -> str:
    pad = " " * n
    return "\n".join((pad + line if line.strip() else "") for line in text.splitlines())


def main() -> int:
    if not WORKFLOW_MD.is_file():
        raise SystemExit(f"workflow source not found: {WORKFLOW_MD}")
    workflow = WORKFLOW_MD.read_text(encoding="utf-8").rstrip()
    OUT_YML.write_text(HEADER + indent(IDENTITY) + "\n\n" + indent(workflow) + "\n", encoding="utf-8")
    print(f"generated {OUT_YML} from {WORKFLOW_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
