import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AutomationSessionStore} from '../../dsh-intelligence-evolution/src/session-origin.js';import {aggregateSessions} from '../src/aggregator.js';
function fixture(t){const root=mkdtempSync(join(tmpdir(),'t07-usage-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const home=join(root,'home'),sessions=join(home,'sessions','--root--'),index=join(home,'intel-joblog');mkdirSync(sessions,{recursive:true});return {root,home,sessions,index};}
function log(f,name,extra={}){mkdirSync(join(f.sessions,name));const file=join(f.sessions,name,'session.v4.jsonl.zstd');writeFileSync(file,'');let seq=0;const event=(type,data)=>JSON.stringify({seq:++seq,time:Date.now(),type,data});const text=[JSON.stringify({version:4,id:name,createdAt:Date.now(),cwd:'/PRIVATE_PATH'}),event('user/message',{content:[{type:'text',text:'学习助手 PRIVATE_PROMPT'}]}),event('request/header',{header:{config:{provider:'actual',model:'fallback'}}}),event('assistant/message',{usage:{inputTokens:10,outputTokens:3,cacheReadTokens:4,cacheWriteTokens:2,...extra}})].join('\n')+'\n';return {file,text};}
test('existing immutable native and audited legacy identities override prompt inference; scope remains unclassified',t=>{const f=fixture(t),a=log(f,'a'),b=log(f,'b');const store=new AutomationSessionStore(f.index);store.record('a',{taskId:'native_task',runId:'native-run',runDate:'2026-10-10'});store.record('b',{taskId:'legacy_task',runId:'legacy-evidence:'+ 'a'.repeat(64),runDate:'2026-10-10'});store.close();const map={[a.file]:a.text,[b.file]:b.text},v=aggregateSessions(f.sessions,7,p=>map[p]);const rows=Object.values(v.byTask);assert.equal(rows.find(r=>r.id==='native_task').classification,'native');assert.equal(rows.find(r=>r.id==='legacy_task').classification,'legacy-evidence');assert.ok(rows.every(r=>r.scope==='unclassified'&&!r.inferred));assert.equal(rows.reduce((n,r)=>n+r.input,0),20);assert.equal(rows.reduce((n,r)=>n+r.messages,0),2);assert.equal(rows.reduce((n,r)=>n+r.cacheRead,0),8);assert.equal(v.byModel['actual/fallback'].input,20);});
test('keywords are visibly heuristic, absent metadata and no matching text remain unknown',t=>{const f=fixture(t),a=log(f,'a'),b=log(f,'b');b.text=b.text.replace('学习助手 PRIVATE_PROMPT','ordinary PRIVATE_PROMPT');const map={[a.file]:a.text,[b.file]:b.text},v=aggregateSessions(f.sessions,7,p=>map[p]);assert.ok(Object.values(v.byTask).some(r=>r.classification==='heuristic'&&r.inferred));assert.ok(Object.values(v.byTask).some(r=>r.classification==='unknown'&&r.id==='unknown'));assert.equal(v.availability.status,'complete');});
test('identical duplicate records and duplicate retained roots count once; conflicting identities fail',t=>{const f=fixture(t),a=log(f,'a'),b=log(f,'b');const line=a.text.trimEnd().split('\n').at(-1);const same=a.text+line+'\n';const v=aggregateSessions(f.sessions,7,()=>same);assert.equal(v.sessions,1);assert.equal(Object.values(v.byDay)[0].input,10);assert.equal(Object.values(v.byTask)[0].messages,1);assert.throws(()=>aggregateSessions(f.sessions,7,p=>p===a.file?a.text:a.text.replace('inputTokens":10','inputTokens":11')),/TOKENLOG_DUPLICATE_CONFLICT/);});
test('malformed, truncated and negative token JSON never produce partial success',t=>{const f=fixture(t),a=log(f,'a');for(const text of [a.text+'{bad}\n',a.text.slice(0,-4),a.text.replace('inputTokens":10','inputTokens":-1')])assert.throws(()=>aggregateSessions(f.sessions,7,()=>text),/TOKENLOG_LOG_INVALID/);});
test('unreadable and missing retained logs fail instead of reporting complete zero',t=>{const f=fixture(t);log(f,'a');assert.throws(()=>aggregateSessions(f.sessions,7,()=>{throw Object.assign(Error('PRIVATE_PATH'),{code:'EACCES'})}),/TOKENLOG_LOG_UNREADABLE/);mkdirSync(join(f.sessions,'0missing'));assert.throws(()=>aggregateSessions(f.sessions,7,()=>''),/TOKENLOG_LOG_MISSING/);});
test('corrupt attribution index cannot silently downgrade to heuristics',t=>{const f=fixture(t),a=log(f,'a');mkdirSync(f.index);writeFileSync(join(f.index,'automation-sessions.sqlite'),'bad');assert.throws(()=>aggregateSessions(f.sessions,7,()=>a.text),/TOKENLOG_METADATA_INVALID/);});
