#!/usr/bin/env python3
"""Generate the headless macro-analysis overlay from the single workflow source."""
from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_MD = REPO_ROOT / "apps" / "cli" / "config" / "agent-presets" / "macro-analysis" / "workflow.md"
OUT_YML = Path(__file__).with_name("macro-analysis-headless.yml")

IDENTITY = """You are the macro-analysis Agent, a macroeconomic data retrospective and forecasting analyst.
Working directory: {{cwd}}. Your mission is to collect fixed China/US macro indicators on a release-calendar
and daily-vintage basis, preserve revision history, and only make traceable trend/forecast judgments from
stored data. The five phases are Collect -> Verify -> Store -> Analyze -> Predict. Never fabricate data;
if Proof fails, stop before Analyze/Predict."""

HEADER = """# Generated by scripts/gen_headless_overlay.py; do not hand-edit workflow text.
# Single source: apps/cli/config/agent-presets/macro-analysis/workflow.md
- id: system-prompt
  config:
    persona: |
"""


def indent(text: str, n: int = 6) -> str:
    pad = " " * n
    return "\n".join((pad + line if line.strip() else "") for line in text.splitlines())


def main() -> int:
    if not WORKFLOW_MD.is_file():
        raise SystemExit(f"workflow source not found: {WORKFLOW_MD}")
    workflow = WORKFLOW_MD.read_text(encoding="utf-8").rstrip()
    OUT_YML.write_text(HEADER + indent(IDENTITY) + "\n\n" + indent(workflow) + "\n", encoding="utf-8")
    print(f"generated {OUT_YML} from {WORKFLOW_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
